name: Build and Test

on:
  push:
    branches: [ "master", "model" ]
  pull_request:
    branches: [ "master", "model" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Initialize
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Clean project
        run: dotnet clean

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run integration tests
        run: docker compose -f Monero.Lws.IntegrationTests/docker-compose.yml run tests

      - name: Cleanup Docker containers
        if: always()
        run: docker compose -f Monero.Lws.IntegrationTests/docker-compose.yml down -v

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/dotcover.xml

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package-${{ github.sha }}
          path: nuget-packages/MoneroLwsNet.1.0.0.nupkg
